apiVersion: v1
kind: Namespace
metadata:
  name: secret-sneaker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sneaker-service-acc
  namespace: secret-sneaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sneaker-cluster-role
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sneaker-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-sneaker-cluster-role
subjects:
- kind: ServiceAccount
  name: secret-sneaker-service-acc
  namespace: secret-sneaker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-controller-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/secret-sneaker-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-controller-pv-claim
  namespace: secret-sneaker
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-controller
  namespace: secret-sneaker
  labels:
    app: custom-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-controller
  template:
    metadata:
      labels:
        app: custom-controller
    spec:
      containers:
        - image: shlokc/secret-sneaker:1.1.0
          name: secret-sneaker-container
          volumeMounts:
            - mountPath: "/mnt/data/secret-sneaker-data"
              name: custom-controller-pv-storage
      serviceAccountName: secret-sneaker-service-acc
      volumes:
        - name: custom-controller-pv-storage
          persistentVolumeClaim:
            claimName: custom-controller-pv-claim
