apiVersion: v1
kind: Namespace
metadata:
  name: secret-mounter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-mounter-service-acc
  namespace: secret-mounter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-mounter-cluster-role
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-mounter-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-mounter-cluster-role
subjects:
- kind: ServiceAccount
  name: secret-mounter-service-acc
  namespace: secret-mounter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-controller
  namespace: secret-mounter
  labels:
    app: custom-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-controller
  template:
    metadata:
      labels:
        app: custom-controller
    spec:
      containers:
        - image: shlokc/secret-mounter:0.0.2
          name: secret-mounter-container
      serviceAccountName: secret-mounter-service-acc
